# -- Site Configuration --
baseURL = "https://simaosilva.com/"
relativeURLs = true
canonifyURLs = true  # Ensures absolute URLs
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

languageCode = "en"

googleAnalytics = "G-SG91FH9B4T"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
