# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://simaosilva.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

languageCode = "en"

googleAnalytics = "G-SG91FH9B4T"

# Update pagination settings to avoid deprecation error
[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
