[[main]]
  name = "Sobre Mim"
  pageRef = "about"
  weight = 20

[[main]]
  name = "CV"
  url = "https://cv.simaosilva.com"
  weight = 30

[[main]]
  name = "Projetos"
  pageRef = "projects"
  weight = 10